### ISSUE TITLE
[레시피] 챕터 번역 참여하겠습니다!

### ISSUE THREAD

**Issue by 22hyeseung** [mskims/redux-saga-in-korean#26]
#### Q. 번역 활동에 감사드립니다! 먼저, [전체 진행 상태 문서](https://github.com/mskims/redux-saga-in-korean/blob/master/transition-progress.md) 를 보시고 번역해주실 챕터 를 알려주세요.

1. 레시피

#### Q. 예상 소요 기간은 어느정도 인가요?
0 일

**Comment by mskims** [comment]
감사합니다! 머지되었습니다: #27
