### ISSUE TITLE
심화 번역해도 될까요?

### ISSUE THREAD

**Issue by guswnsxodlf** [mskims/redux-saga-in-korean#3]
번역 하고싶습니다!

**Comment by mskims** [comment]
네 그럼요 감사합니다 ^^

**Comment by mskims** [comment]
어떤 챕터까지 하실건가요?

**Comment by guswnsxodlf** [comment]
되도록이면 모두 하고 싶은데.. 일단은 첫 3개만 하도록 하겠습니다.
리드미와 첫번째 글 PR 보내도록 하겠습니다!
Milestone 생성 부탁드릴게요~
아, 그리고 advanced 브랜치도 생성해주실수 있나요??

**Comment by mskims** [comment]
@guswnsxodlf advanced 브랜치로 PR 보내실 생각이신가요? 알겠습니다 감사합니다 ^^
