### ISSUE TITLE
원문 비교 탈자

### ISSUE THREAD

**Issue by mingoos** [mskims/redux-saga-in-korean#38]
항목, 고급 개념 => 병렬 태스크 실행 파트 하단 코드에 원문과 다른 부분이 있습니다.
=> 원문에서는 yield all([...]), 번역 본에는 all[...] 

원문
`
const [users, repos] = yield all([
  call(fetch, '/users'),
  call(fetch, '/repos')
])
`
번역
`
const [users, repos]  = yield all[
  call(fetch, '/users'),
  call(fetch, '/repos')
]
`

**Comment by soulwawa** [comment]
수정 완료 되었습니다 #39
